name: "NPM Release"

on:
  release:
    types: [published]

jobs:
  release:
    name: "@nthity/validation publish"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.2
      - name: node
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 17
          registry-url: https://registry.npmjs.org
      - name: publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
